[package]
name = "tokio-linux-zio"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
license = "MIT"
description = "Linux zero-copy IO"
categories = ["cryptography", "network-programming"]
edition = "2018"

[dependencies]
tokio = "0.1"
nix = "0.11"

[dev-dependencies]
lazy_static = "1"
